PointfootCfg:
  init_state:
    joint_names:
      - "abad_L_Joint"
      - "hip_L_Joint"
      - "knee_L_Joint"
      - "ankle_L_Joint"
      - "abad_R_Joint"
      - "hip_R_Joint"
      - "knee_R_Joint"
      - "ankle_R_Joint"
      - "J1"
      - "J2"
      - "J3"
      - "J4"
      - "J5"
      - "J6"
    # target angles [rad] when action = 0.0
    default_joint_angle:
      abad_L_Joint: 0.0
      hip_L_Joint: 0.0
      knee_L_Joint: 0.0
      ankle_L_Joint: 0.0

      abad_R_Joint: 0.0
      hip_R_Joint: 0.0
      knee_R_Joint: 0.0
      ankle_R_Joint: 0.0

      J1: 0.0
      J2: 0.0
      J3: 0.0
      J4: 0.0
      J5: 0.0
      J6: 0.0
    
    init_stand_joint_angle:
      abad_L_Joint: 0.0
      hip_L_Joint: 0.58
      knee_L_Joint: 1.35
      ankle_L_Joint: -0.8

      abad_R_Joint: 0.0
      hip_R_Joint: -0.58
      knee_R_Joint: -1.35
      ankle_R_Joint: -0.8

      J1: 0.0
      J2: 0.0
      J3: 0.0
      J4: 0.0
      J5: 0.0
      J6: 0.0

  control:
    # PD Drive parameters:
    leg_joint_stiffness: 40.0 #50
    leg_joint_damping: 2.5 #6

    ankle_joint_stiffness:  15.0
    ankle_joint_damping: 2.0 #1

    arm_j123_stiffness: 18
    arm_j123_damping: 1
    arm_j456_stiffness: 4
    arm_j456_damping: 0.5

    action_scale_pos: 0.25
    # action_scale_vel: 3 #4
    decimation: 10

    leg_joint_torque_limit: 80
    ankle_joint_torque_limit: 40
    arm_j123_torque_limit: 18
    arm_j456_torque_limit: 3
  
  gait:
    frequencies: 1.3
    swing_height: 0.12
  
  estimation:
    threshold: 0.55
    threshold_count: 100

  normalization:
    encoder_normalize: True
    clip_scales:
      clip_observations: 100.
      clip_actions: 100.
    obs_scales:
      lin_vel: 2.0
      ang_vel: 0.25
      dof_pos: 1.0
      dof_vel: 0.05
      height_measurements: 5.0

  user_cmd_scales:
    lin_vel_x: 3.0
    lin_vel_y: 2.0
    ang_vel_yaw: 1.2

  size:
    actions_size: 14 
    observations_size: 81 # 3+3 + 3+3+6 + 14 + 14 + 14 + 3 +2
    commands_size: 5
    obs_history_length: 5
    encoder_output_size: 64
    one_hot_encoder_output_size: 2
    gait_generator_output_size: 32

  
  imu_orientation_offset:
    roll: 0.0
    pitch: 0.00
    yaw: 0.0
